### PR TITLE
WIP/possibly to abandon: Revert back to formatting by length by default

### PR DESCRIPTION
**Pull request by ghost**
Given the new setting, using the same configuration file now leads to
completely different results.

Via https://github.com/someth2say/xmlformat/pull/5#pullrequestreview-619535809:
> I would propose, for the sake of retro-compatibility, to default the
>  wrap-type to sentence.
    
Tbh, I don't quite understand that sentence -- this is explicitly
breaking compatibility with existing configuration files.

### CODE REVIEW

**Comment by someth2say** [comment]
The idea was, as per [this](https://github.com/someth2say/xmlformat/pull/5/files?file-filters%5B%5D=.conf&file-filters%5B%5D=.rb#diff-ff836192619e9ca26d51467983cba9ea82b8a479ac7928a3a36c4a4d9c79a7f7L950[), that all normalized elements were previously sentence-broken.
So we made it the default after the changes.

It took me some time until I found you are partially right, and we broke some compatibility!
Previously, **only normalized elements** were sentence-broken.
But the current change is that **all elements** are sentence-broken, despite they are normalized or not.

Indeed this should be fixed, but I don't thing that making "length" the default is the right option.

**Comment by someth2say** [comment]
I was wrong, I added a test and the code is right, breaking only normalized elements.
Can you please add an example or reproducer? I would understand how the old behaviour works for you, and how the new one changes anything.

**Comment by ghost** [comment]
We're using this [config file](https://github.com/openSUSE/daps/blob/main/etc/docbook-xmlformat.conf) + xmlformat.pl and noticed that behavior has changed since we updated from the Kitebird version to the version from this repo. I verified that with my updates here, at least the Perl version works the same way it did before.

**Comment by someth2say** [comment]
I got you now.
I never intended to keep backwards compatibility with Kitebird's version, but with older versions for this xmlformat.
This fork have breaking changes compared to Kitebird's, such as the one-sentence-per-line normalization. 

If you need to change the default behavior, you can easily include a `*DEFAULT`section in your configuration file:
```
*DEFAULT
  wrap-length = 80
  wrap-type = length
```

Anyway, I would like to know what is the impact for you of this behavior.
Are you migrating form Kitebird´s version to this one?
Does adding the `*DEFAULT` section causes any trouble?

I´m open to discussion, but I would like to have the whole picture so I can discuss the impact with other power users.

**Comment by ghost** [comment]
Thanks for the questions and suggestions!

> Are you migrating form Kitebird´s version to this one?

Yes, on the openSUSE side, @tomschr and @tbazant have replaced the RPM of the Kitebird version with this version (right now, only in a non-standard repo, however).

The logistics issue I see is that our writers need to update both the package with the config file in it and the xmlformat package at the same time. I realize RPM allows for versioned dependencies, but that would only help us in one direction, config file package -> xmlformat, but would not make sense in the other direction. It also doesn't address the issue that both packages are on different non-standard RPM repos and most people will likely only have enabled one of these repos.

Ultimately, I suspect we'll live. :)

> Does adding the *DEFAULT section causes any trouble?

So ... I didn't previously realize that the entire `wrap-type` setting was never available in the Kitebird version, making a config file with such a `*DEFAULT` explicitly incompatible with the Kitebird version (it will just error out because of an unknown setting).

Also, it appears that the previous default was essentially `wrap-type = none`, unless you set `wrap-length`.

(What's a little suboptimal in the design of the new setting is that you can now set `wrap-type = none` + `wrap-length = 80` and the outcome will be that the content will not be wrapped. Or `wrap-type = sentence` + `wrap-length = 80` and it will wrap at the end of sentences, even if they're longer than 80 characters. It would be neater if there was a single setting that did not leave such a potential for errors.)

**Comment by ghost** [comment]
Ok. I think I am closing this, we'll have to solve this downstream. More feedback welcome, if you have any. :)

**Comment by someth2say** [comment]
I see many people is requesting backward compatibility with Kitebird's version, so I'm opening this PR back, and see if I can find a good solution.

**Pull request closed without merging**
